// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Truman.Data;

#nullable disable

namespace Truman.Data.Migrations
{
    [DbContext(typeof(TrumanDbContext))]
    [Migration("20250817040659_AddUserTagPreferences")]
    partial class AddUserTagPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Truman.Data.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adventure")
                        .HasColumnType("integer");

                    b.Property<int>("Ambition")
                        .HasColumnType("integer");

                    b.Property<int>("Compassion")
                        .HasColumnType("integer");

                    b.Property<int>("Connection")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Creativity")
                        .HasColumnType("integer");

                    b.Property<int>("Discipline")
                        .HasColumnType("integer");

                    b.Property<int>("Equality")
                        .HasColumnType("integer");

                    b.Property<int>("Freedom")
                        .HasColumnType("integer");

                    b.Property<int>("Honesty")
                        .HasColumnType("integer");

                    b.Property<int>("Independence")
                        .HasColumnType("integer");

                    b.Property<int>("Justice")
                        .HasColumnType("integer");

                    b.Property<int>("Knowledge")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Loyalty")
                        .HasColumnType("integer");

                    b.Property<int>("Obedience")
                        .HasColumnType("integer");

                    b.Property<int>("OpenMindedness")
                        .HasColumnType("integer");

                    b.Property<int>("PeaceOfMind")
                        .HasColumnType("integer");

                    b.Property<int>("Pleasure")
                        .HasColumnType("integer");

                    b.Property<int>("Responsibility")
                        .HasColumnType("integer");

                    b.Property<int>("RssItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Security")
                        .HasColumnType("integer");

                    b.Property<int>("SelfActualization")
                        .HasColumnType("integer");

                    b.Property<int>("SelfRespect")
                        .HasColumnType("integer");

                    b.Property<int>("Sentiment")
                        .HasColumnType("integer");

                    b.Property<int>("Success")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tldr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tradition")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.HasIndex("RssItemId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Truman.Data.Entities.ArticlePresenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PresenterId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tldr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PresenterId");

                    b.HasIndex("ArticleId", "PresenterId")
                        .IsUnique();

                    b.ToTable("ArticlePresenters");
                });

            modelBuilder.Entity("Truman.Data.Entities.MagicLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MagicLinks");
                });

            modelBuilder.Entity("Truman.Data.Entities.Presenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PresenterStyle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PresenterStyle")
                        .IsUnique();

                    b.ToTable("Presenters");
                });

            modelBuilder.Entity("Truman.Data.Entities.RssItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PubDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TimeAnalysed")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.ToTable("RssItems");
                });

            modelBuilder.Entity("Truman.Data.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mood")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Truman.Data.Entities.UserTagPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Tag")
                        .IsUnique();

                    b.ToTable("UserTagPreferences");
                });

            modelBuilder.Entity("Truman.Data.Entities.Article", b =>
                {
                    b.HasOne("Truman.Data.Entities.RssItem", "RssItem")
                        .WithMany()
                        .HasForeignKey("RssItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RssItem");
                });

            modelBuilder.Entity("Truman.Data.Entities.ArticlePresenter", b =>
                {
                    b.HasOne("Truman.Data.Entities.Article", "Article")
                        .WithMany("ArticlePresenters")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Truman.Data.Entities.Presenter", "Presenter")
                        .WithMany()
                        .HasForeignKey("PresenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Presenter");
                });

            modelBuilder.Entity("Truman.Data.Entities.UserTagPreference", b =>
                {
                    b.HasOne("Truman.Data.Entities.UserProfile", "UserProfile")
                        .WithMany("TagPreferences")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Truman.Data.Entities.Article", b =>
                {
                    b.Navigation("ArticlePresenters");
                });

            modelBuilder.Entity("Truman.Data.Entities.UserProfile", b =>
                {
                    b.Navigation("TagPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
